package com.model;

/**
 * TShipin generated by MyEclipse Persistence Tools
 */

public class TShipin implements java.io.Serializable
{

	// Fields

	private Integer shipinId;

	private String shipinName;

	private String shipinJianjie;
	
	private String shipinZhuyan;
	
	private String shipinDaoyan;
	
	private String shipinLeixing;
	

	private String shipinBofangshijian;

	private String shipinFabushijian;

	private String shipinPath;

	private String shipinYuanshiming;
	
	private int shipinCishu;
	
	private String del;

	// Constructors

	/** default constructor */
	public TShipin()
	{
	}

	/** full constructor */
	public TShipin(String shipinName, String shipinJianjie,
			String shipinBofangshijian, String shipinFabushijian,
			String shipinPath, String shipinYuanshiming)
	{
		this.shipinName = shipinName;
		this.shipinJianjie = shipinJianjie;
		this.shipinBofangshijian = shipinBofangshijian;
		this.shipinFabushijian = shipinFabushijian;
		this.shipinPath = shipinPath;
		this.shipinYuanshiming = shipinYuanshiming;
	}

	// Property accessors

	public Integer getShipinId()
	{
		return this.shipinId;
	}

	public String getDel()
	{
		return del;
	}
	

	public String getShipinDaoyan()
	{
		return shipinDaoyan;
	}

	public int getShipinCishu()
	{
		return shipinCishu;
	}

	public void setShipinCishu(int shipinCishu)
	{
		this.shipinCishu = shipinCishu;
	}

	public void setShipinDaoyan(String shipinDaoyan)
	{
		this.shipinDaoyan = shipinDaoyan;
	}

	public String getShipinLeixing()
	{
		return shipinLeixing;
	}

	public void setShipinLeixing(String shipinLeixing)
	{
		this.shipinLeixing = shipinLeixing;
	}

	public String getShipinZhuyan()
	{
		return shipinZhuyan;
	}

	public void setShipinZhuyan(String shipinZhuyan)
	{
		this.shipinZhuyan = shipinZhuyan;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public void setShipinId(Integer shipinId)
	{
		this.shipinId = shipinId;
	}

	public String getShipinName()
	{
		return this.shipinName;
	}

	public void setShipinName(String shipinName)
	{
		this.shipinName = shipinName;
	}

	public String getShipinJianjie()
	{
		return this.shipinJianjie;
	}

	public void setShipinJianjie(String shipinJianjie)
	{
		this.shipinJianjie = shipinJianjie;
	}

	public String getShipinBofangshijian()
	{
		return this.shipinBofangshijian;
	}

	public void setShipinBofangshijian(String shipinBofangshijian)
	{
		this.shipinBofangshijian = shipinBofangshijian;
	}

	public String getShipinFabushijian()
	{
		return this.shipinFabushijian;
	}

	public void setShipinFabushijian(String shipinFabushijian)
	{
		this.shipinFabushijian = shipinFabushijian;
	}

	public String getShipinPath()
	{
		return this.shipinPath;
	}

	public void setShipinPath(String shipinPath)
	{
		this.shipinPath = shipinPath;
	}

	public String getShipinYuanshiming()
	{
		return this.shipinYuanshiming;
	}

	public void setShipinYuanshiming(String shipinYuanshiming)
	{
		this.shipinYuanshiming = shipinYuanshiming;
	}

}